<?php
// Database Type : "MySQL"
// Database Adapter : "mysql"
$dmxConnectionString = "mysql:host=localhost;port=;dbname=designsuu;charset=utf8;user=root;password=root";
$dmxConnectionLimit = 1000;
$dmxConnectionDebug = false;

$dmxConnectionMeta = <<<JSON
{"allTables": ["course", "course_season_year", "images", "instructor", "projects", "season", "season_year", "students", "students_projects_course", "year"], "allViews": [], "tables": {"course": {"columns": {"id": {"type": "int", "primary": true}, "shortName": {"type": "varchar", "size": 11, "nullable": true}, "courseName": {"type": "varchar", "size": 27, "nullable": true}, "courseNumber": {"type": "varchar", "size": 31, "nullable": true}, "description": {"type": "longtext", "size": 4294967295, "nullable": true}}}, "course_season_year": {"columns": {"id": {"type": "int", "primary": true}, "courseID": {"type": "int", "nullable": true}, "seasonID": {"type": "int", "nullable": true}, "yearID": {"type": "int", "nullable": true}, "professorID": {"type": "int", "nullable": true}}}, "season": {"columns": {"id": {"type": "int", "primary": true}, "seasonName": {"type": "varchar", "size": 21, "nullable": true}}}, "year": {"columns": {"id": {"type": "int", "primary": true}, "year": {"type": "year", "nullable": true}, "active": {"type": "tinyint", "nullable": true}}}, "instructor": {"columns": {"id": {"type": "int", "primary": true}, "firstName": {"type": "varchar", "size": 30, "nullable": true}, "lastName": {"type": "varchar", "size": 40, "nullable": true}, "url": {"type": "varchar", "size": 122, "nullable": true}}}, "images": {"columns": {"id": {"type": "int", "primary": true}, "filename": {"type": "varchar", "size": 122, "nullable": true}, "link": {"type": "varchar", "size": 210, "nullable": true}, "projectID": {"type": "int", "nullable": true}, "studentID": {"type": "int", "nullable": true}, "courseID": {"type": "int", "nullable": true}}}, "projects": {"columns": {"id": {"type": "int", "primary": true}, "projectNum": {"type": "int", "nullable": true}, "projectFilename": {"type": "varchar", "size": 75, "nullable": true}, "projectURL": {"type": "varchar", "size": 255, "nullable": true}, "studentID": {"type": "int", "nullable": true}}}, "students": {"columns": {"id": {"type": "int", "primary": true}, "firstName": {"type": "varchar", "size": 75, "nullable": true}, "lastName": {"type": "varchar", "size": 75, "nullable": true}}}}}
JSON;
?>